---

- pre_tasks:
  hosts: all
  connection: local
  gather_facts: False
  sudo: False
  vars:
    slack_pre_data: 'payload={"channel": "#deploy", "username": "ansible deploy", "text": "Starting deploy to <{{ pepyatka_frontend_scheme }}://{{ pepyatka_hostname }}|{{ pepyatka_hostname }}>", "icon_emoji": ":ghost:"}'
  tasks:
    - name: Delete saved pepyatka-server and pepyatka-html changelogs
      file: path={{ item }} state=absent
      with_items:
        - pepyatka-server-changelog
        - pepyatka-html-changelog
      when: slack_notification_url is defined
      tags:
        - changelog
    - name: Send a notification to Slack
      uri:
        method: POST
        url: "{{ slack_notification_url }}"
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        body: "{{ slack_pre_data }}"
      when: slack_notification_url is defined
      tags:
        - slack

- include: elasticsearch.yml
- include: redis.yml
- include: pepyatka.yml
- include: nginx.yml

- post_tasks:
  hosts: all
  connection: local
  gather_facts: False
  sudo: False
  vars:
    slack_post_data: 'payload={"channel": "#deploy", "username": "ansible deploy", "text": "Successfully deployed <{{ pepyatka_frontend_scheme }}://{{ pepyatka_hostname }}|{{ pepyatka_hostname }}>", "icon_emoji": ":ghost:"}'
  tasks:
    - name: Generate pepyatka-server changelog message for Slack
      shell: echo "Updated pepyatka-server on {{ item | basename }}. <{{ pepyatka_server_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-server-changelog/*
      register: pepyatka_server_changelog
      when: slack_notification_url is defined
      tags:
        - changelog

    - name: Generate pepyatka-html changelog message for Slack
      shell: echo "Updated pepyatka-html on {{ item | basename }}. <{{ pepyatka_html_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-html-changelog/*
      register: pepyatka_html_changelog
      when: slack_notification_url is defined
      tags:
        - changelog

    - name: Notify Slack about pepyatka-server changes
      uri:
        method: POST
        url: "{{ slack_notification_url }}"
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        body: 'payload={"channel": "#deploy", "username": "ansible deploy", "text": "{{ item.stdout }}", "icon_emoji": ":ghost:"}'
      with_items: pepyatka_server_changelog.results
      when: slack_notification_url is defined and pepyatka_server_changelog.changed
      tags:
        - slack

    - name: Notify Slack about pepyatka-html changes
      uri:
        method: POST
        url: "{{ slack_notification_url }}"
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        body: 'payload={"channel": "#deploy", "username": "ansible deploy", "text": "{{ item.stdout }}", "icon_emoji": ":ghost:"}'
      with_items: pepyatka_html_changelog.results
      when: slack_notification_url is defined and pepyatka_html_changelog.changed
      tags:
        - slack

    - name: Send a generic notification to Slack
      uri:
        method: POST
        url: "{{ slack_notification_url }}"
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        body: "{{ slack_post_data }}"
      when: slack_notification_url is defined
            and not pepyatka_server_changelog.changed
            and not pepyatka_html_changelog.changed
      tags:
        - slack

